apiVersion: v1
kind: Service
metadata:
  name: migration-demo
  namespace: migration-demo
spec:
  selector:
    app: migration-demo
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
